const { signUpHandler, signInHandler } = require('./common');
const {
  signoutHandler,
  getFavoriteHandler,
  addFavoriteHandler,
  deleteFromFavoriteHandler,
  getCartHandler,
  addCartProductHandler,
  getProfileUserId,
  putProfileUser,
  deleteFromCartHandler,
  getUserOrders,
  addUserOrdersById,
  updateCartHandler,
  isAuth,
} = require('./buyer');
const {
  addProductHandler,
  putProductHandler,
  getClientsHandler,
  getOrdersHandler,
  deleteProductHandler,
  searchHandler,
} = require('./seller');

module.exports = {
  signUpHandler,
  signInHandler,
  signoutHandler,
  addProductHandler,
  putProductHandler,
  getFavoriteHandler,
  addFavoriteHandler,
  deleteFromFavoriteHandler,
  getCartHandler,
  addCartProductHandler,
  deleteFromCartHandler,
  updateCartHandler,
  getClientsHandler,
  getOrdersHandler,
  getUserOrders,
  addUserOrdersById,
  getProfileUserId,
  putProfileUser,
  deleteProductHandler,
  searchHandler,
  isAuth,
};
